name = "Cactus"
license = "MIT"
licenselink = "https://github.com/ischaojie/hugo-theme-cactus/blob/master/LICENSE"
description = "A clean, responsive hugo theme for personal blog. Forked from hexo theme cactus created by @probberechts."
homepage = "https://github.com/ischaojie/hugo-theme-cactus"
demosite = "https://blog.chaojie.fun/"
tags = ["blog", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.55"

[author]
    name = "chaojie"
    homepage = "https://github.com/ischaojie"

# If porting an existing theme
[original]
    author = "Pieter Robberechts"
    homepage = "https://github.com/probberechts"
    repo = "https://github.com/probberechts/hexo-theme-cactus"
